version: '3'

services:
  nextjs:
    build: .
    image: nextjs-app
    ports:
      - "3000:3000"
      - "6000:6000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user123
      - DB_PASSWORD=password123
      - DB_NAME=hr-system
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: hr-system
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
