version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: hr-system

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "6000:6000"  # Map port 6000 on host to port 6000 in container
    depends_on:
      - db
