
###
GET http://localhost:6000/api

###
GET http://localhost:6000/check

###
POST http://localhost:6000/api
Content-Type: application/json

{
    "name": "tom",
    "location": "1234"
}

###
GET http://localhost:6000/users

###
POST http://localhost:6000/insert-users

###
GET http://localhost:6000/setup

###
POST http://localhost:6000/api/register
Content-Type: application/json

{
    "name": "test1",
    "email": "test@example.com",
    "password": "password123"
}